server:
  port: 8078

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_service
    username: springstudent
    password: springstudent
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    banner-mode: off
  application:
    name: payment-service
app:
  routesController:
    requestmapping:
      paymentServiceController: /paymentservice
  routes:
    orderList:
      getOrderList: /getorderlist
      createOrder: /createorder
      deleteByProductCode: /deleteorderbyproductcode
    balance:
      getBalance: /getbalance
      addBalance: /addbalance
      createBalance: /createbalance
  microservicePaths:
    tokenService:
      extractUsername: http://localhost:8079/tokenservice/extractusername
    productService:
      getProductInfo: http://localhost:8083/productservice/product/getproductinfo